### ISSUE TITLE
Fix typos

### ISSUE THREAD

**Issue by Kr0ff** [browninfosecguy/ADLab#3]
Not really an issue, mostly typos in README.md...
=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
Usage: This "~~Scirpt~~" -> "script" can be used to configure both Domain Controller and Workstation.

Option 2: Install the "Active Directory Domain Services" role on the server and configure "~~Domian~~" -> "Domain" Controller.

Option 7: Join the "~~wrokstation~~" -> "workstation" to the Domain.

**Comment by Kr0ff** [comment]
Checked the script, sry should've done it before i posted the issue...

Anyway, same typos above extend to the script as well in $ADLab (line: 334) var

**Comment by browninfosecguy** [comment]
Correction made. Thanks
